server:
  port: 12001

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/

logging:
  level:
    org.springframework.cloud.gateway: info